packages:
  base: !include node_base.yaml

substitutions:
  node_name:    "jarvis-node-laundry-room"
  room_display: "Laundry Room"
  room_id:      "laundry_room"
  node_ip:      !secret node_laundry_room_ip
